Repository wirriamm/ask-aunty, pull requests merged in 2020-07, with the labels that each got.

#69 Swipe feature
  app/javascript/controllers/polls_controller.js
  app/views/meals/setup.html.erb
Labels: enhancement

#73 Cuisine has many photos
  app/models/cuisine.rb
  app/views/meals/_verdict.html.erb
  app/views/meals/setup.html.erb
  db/seeds.rb
Labels: db

#77 Fix navbar
  Gemfile
  Gemfile.lock
  app/views/shared/_navbar.html.erb
Labels: bug

#83 Meal show
  app/controllers/meals_controller.rb
  app/javascript/controllers/show_button_controller.js
  app/views/meals/index.html.erb
  app/views/meals/show.html.erb
Labels: user story

#82 Set pax
  app/controllers/meals_controller.rb
  app/models/meal.rb
  app/views/meals/new.html.erb
  app/views/pages/home.html.erb
  db/migrate/20200704165211_add_pax_to_meals.rb
  db/schema.rb
Labels: SHOULD HAVE, db, views

#88 Api Call
  app/controllers/meals_controller.rb
  app/controllers/verdicts_controller.rb
  app/models/restaurant.rb
  app/models/verdict.rb
  app/views/meals/_verdict.html.erb
  app/views/meals/result.html.erb
  config/application.rb
  db/migrate/20200707122339_create_verdicts.rb
  db/migrate/20200707151041_create_restaurants.rb
  db/migrate/20200707154537_add_cuisine_reference_to_restaurant.rb
  db/schema.rb
  test/controllers/verdicts_controller_test.rb
  test/models/restaurant_test.rb
  test/models/verdict_test.rb
Labels: enhancement

#86 Added wa and tele share buttons
  app/controllers/meals_controller.rb
  app/views/meals/show.html.erb
  db/schema.rb
Labels: SHOULD HAVE, views

#89 UI kit
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_input_field.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/config/_simple_form.scss
  app/assets/stylesheets/pages/_background.scss
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_text.scss
  app/controllers/pages_controller.rb
  app/views/pages/ui_kit.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: enhancement, views

#91 Style result
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_rating.scss
  app/assets/stylesheets/config/_fonts.scss
  app/assets/stylesheets/pages/_background.scss
  app/controllers/meals_controller.rb
  app/views/meals/_verdict.html.erb
  app/views/meals/result.html.erb
  db/migrate/20200709120710_add_price_level_to_restaurants.rb
  db/migrate/20200710052805_rename_column_in_restaurants.rb
  db/schema.rb
Labels: enhancement

#98 modified navbar
  app/assets/stylesheets/components/_avatar.scss
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: enhancement

#112 added down arrow to represent expandable area in verdict partial
  app/views/meals/_verdict.html.erb
Labels: enhancement

#110 Push email notification
  Gemfile
  Gemfile.lock
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  app/views/user_mailer/all_pax_completed_email.html.erb
  app/views/user_mailer/endtime_is_over_email.html.erb
  app/views/user_mailer/push_email.text.erb
  app/workers/hard_worker.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/sidekiq.rb
  config/initializers/smtp.rb
  config/schedule.yml
  db/migrate/20200711150336_add_is_notified_to_meals.rb
  db/migrate/20200711150545_change_is_notified_in_meals.rb
  db/schema.rb
  test/mailers/previews/user_mailer_preview.rb
  test/mailers/user_mailer_test.rb
  test/workers/hard_worker_test.rb
Labels: enhancement

#118 Flow 1
  app/controllers/meals_controller.rb
  app/javascript/controllers/journey_controller.js
  app/javascript/controllers/show_button_controller.js
  app/views/meals/show.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: enhancement

#119 can update pax and time in controller
  app/controllers/meals_controller.rb
Labels: controller
