Repository wirriamm/ask-aunty, pull requests merged in 2020-06, with the labels that each got.

#11 seed preferences
  app/models/preference.rb
  db/migrate/20200620043600_create_preferences.rb
  db/schema.rb
  db/seeds.rb
  test/models/preference_test.rb
Labels: MUSTHAVE

#18 Meals model
  app/models/meal.rb
  db/migrate/20200620065500_create_meals.rb
  db/schema.rb
  test/models/meal_test.rb
Labels: MUSTHAVE, db

#20 generated meals controller
  app/controllers/meals_controller.rb
  app/views/meals/new.html.erb
  app/views/meals/show.html.erb
  test/controllers/meals_controller_test.rb
Labels: db

#27 updated cuisines seeds
  db/migrate/20200623135957_add_dish_to_cuisines.rb
  db/seeds.rb
Labels: db, seeds

#33 User can view photo of 10 cuisines
  app/controllers/meals_controller.rb
  app/controllers/polls_controller.rb
  app/views/meals/result.html.erb
  app/views/meals/setup.html.erb
  config/routes.rb
  test/controllers/polls_controller_test.rb
Labels: MUSTHAVE, user story

#32 Landing page basics
  app/assets/images/aunty-1.svg
  app/assets/images/aunty.svg
  app/controllers/pages_controller.rb
  app/views/layouts/application.html.erb
  app/views/meals/createmeal.html.erb
  app/views/meals/joinmeal.html.erb
  app/views/meals/new.html.erb
  app/views/meals/show.html.erb
  app/views/pages/create_meal.html.erb
  app/views/pages/home.html.erb
  app/views/pages/join_meal.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20200624022437_add_postal_code_to_meals.rb
  db/schema.rb
Labels: MUSTHAVE, user story, views

#37 Stylesheet Part 2
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/config/_fonts.scss
  app/views/meals/_verdict.html.erb
  app/views/meals/nearby-restaurants.html.erb
  app/views/pages/home.html.erb
Labels: enhancement, views

#38 Meals related
  Gemfile
  Gemfile.lock
  app/controllers/meals_controller.rb
  app/controllers/pages_controller.rb
  app/javascript/controllers/hello_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/newmeal_controller.js
  app/javascript/packs/application.js
  app/models/meal.rb
  app/views/meals/_vanity_id.html.erb
  app/views/meals/new.html.erb
  app/views/pages/create_meal.html.erb
  app/views/pages/join_meal.html.erb
  config/application.rb
  config/routes.rb
  package.json
  yarn.lock
Labels: MUSTHAVE, controller

#40 Preferences pagge
  app/controllers/meals_controller.rb
  app/controllers/preferences_controller.rb
  app/models/meal.rb
  app/models/preference.rb
  app/models/user.rb
  app/models/users_preference.rb
  app/views/preferences/index.html.erb
  config/routes.rb
  db/migrate/20200625115133_create_users_preferences.rb
  db/migrate/20200625122958_add_status_to_users_preferences.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/preferences_controller_test.rb
  test/models/users_preference_test.rb
Labels: MUSTHAVE, controller, user story

#41 updated user flow for initiating meal
  app/controllers/meals_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/preferences_controller.rb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: MUSTHAVE, bug

#42 Resultsui
  app/controllers/meals_controller.rb
  app/models/meal.rb
  app/views/meals/_verdict.html.erb
  app/views/meals/result.html.erb
  app/views/meals/setup.html.erb
  app/views/shared/_navbar.html.erb
  db/seeds.rb
Labels: MUSTHAVE, user story, views

#45 UI polls
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_poll.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/pages/_home.scss
  app/controllers/meals_controller.rb
  app/views/layouts/application.html.erb
  app/views/meals/setup.html.erb
  app/views/pages/home.html.erb
  app/views/pages/join_meal.html.erb
Labels: enhancement

#48 alert for meal ID
  app/controllers/meals_controller.rb
  app/views/shared/_flashes.html.erb
Labels: MUSTHAVE, enhancement, views

#49 UI polls - View Result button
  app/assets/stylesheets/components/_poll.scss
Labels: bug

#65 bg color and navbar stick
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/shared/_navbar.html.erb
Labels: enhancement
